# Page settings
baseurl = "https://blockchaincr.com"
title = "Blockchain Costa Rica"
languageCode = "es-es"

[params]
  # Meta
  author = "gaboesquivel.com"
  description = "Dedicados al estudio e implementación de la tecnología blockchain en sus diferentes áreas de aplicación."
  email = ""

  # Services section
  [params.services]
    enable = true

    [[params.services.item]]
      title = "Banca y Finanzas"
      description = "Pagos, mercados de capital, finanzas comerciales, complimiento y auditoría, conozca su cliente, anti-lavado, seguros, transacciones de punto a punto y más."
      icon = "fa fa-university"

    [[params.services.item]]
      title = "Internet de las cosas"
      description = "Comunicación maquína a maquína (M2M) intra e inter compañías, gestión de identidades, automatización de procesos industriales, picopagos en tiempo real y más."
      icon = "fa fa-connectdevelop"

    [[params.services.item]]
      title = "Empresas"
      description = "Logística & gestión de activos, cadenas de suministros, salud, media, energía y más."
      icon = "fa fa-truck"

      [[params.services.item]]
      title = "Gobierno"
      description = "Manejo de registros, manejo de identidad, votaciones, impuestos, transparencia de gobierno, legislación, cumplimiento, regulación y más."
      icon = "fa fa-id-card"

  # About section
  [params.about]
    enable = true
    title = "Equipo"
    description = "Nuestro equipo de líderes experimentados de negocios, producto y tecnología."

    [[params.about.item]]
      name = "Uriel Herrera"
      position = "Business Intelligence"
      description = "Blockchain / IoT / Inteligencia Artificial. Creo fervientemente que la combinación de estas tecnologías puede sentar un antes y un después en la manera en que comprendemos el mundo."
      img = "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAqNAAAAJDQzYzVmYTlkLTFjZWYtNDIzMC05Yjg0LWJkNWU2MTZkZDA3Yw.jpg"
      alt = "Uriel Herrera"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Gabo Esquivel"
      position = "Fintech, Cloud, OSS"
      description = "Desarollador de software especializándose en la construcción de soluciones en para servicios financieros utilizando computación en la nube, arquitecturas serverless y código abierto."
      img = "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAdKAAAAJDNlMGJhZWZhLTFjZDUtNDY0ZC1iNmUzLWEwMDMwZWEzYTY1Yw.jpg"
      alt = "Gabo Esquivel"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Walter Montes"
      position = "Desarrollo de Producto"
      description = "Pasó de la ingeniería y el liderazgo de los equipos de software al diseño centrado en el usuario de soluciones tecnológicas en torno a cloud, inteligencia artificial y plataformas abiertas."
      img = "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAsGAAAAJGQ4MGRlODM4LTk0NzQtNDJiYS1iYjlkLTBhMzNmMzk3MGJiYw.jpg"
      alt = "Walter Montes"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]

  # Contact section
  [params.contact]
    enable = true
    title = "Contáctanos"
    description = "Nos interesa muchísimo escuchar tus ideas, consultas y comentarios. Déjamos un mensaje y te responderemos a la mayor brevedad posible."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "San José, Costa Rica"],
        # ["icon-phone", "6360-9999"],
        # ["icon-envelope", "info@blockchaincr.com"]
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Blockchain Costa Rica. All Rights Reserved. <br>Website por <a href="http://gaboesquivel.com/" target="_blank">gaboesquivel.com</a>'
